version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mascd_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mascd_backend
    restart: unless-stopped
    env_file: .env
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      PORT: ${PORT_BACKEND}
      VERIFY_RATE_LIMIT_PER_MIN: ${VERIFY_RATE_LIMIT_PER_MIN}
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "${PORT_BACKEND}:3001"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mascd_frontend
    restart: unless-stopped
    env_file: .env
    environment:
      VITE_API_BASE: ${VITE_API_BASE}
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "${PORT_FRONTEND}:5173"
    depends_on:
      - backend

volumes:
  mysql_data: